framework:
    notifier:
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
        channel_policy:
            urgent: ['email', 'chat/telegram']
            high: ['email', 'chat/telegram']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: '%env(ADMIN_EMAIL)%' }
