# Конфигурация интернационализации (i18n)
# Requirements: 4.1, 4.3

framework:
    default_locale: ru
    enabled_locales: ['en', 'ru']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['ru', 'en']
